/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bracelet({ scale = [25, 25, 25], position = [-2, 0, -0.5]}) {
  const { nodes, materials } = useGLTF('/braceletOSKI.glb')
  return (
    <group scale={scale} position={position} dispose={null}>
      <group position={[-0.455, -0.076, -0.539]} scale={0.002}>
        <group position={[119.197, 0, 0]}>
          <group
            position={[-37.421, 179.812, 474.859]}
            rotation={[1.168, 1.207, -0.053]}
            scale={0.531}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder.geometry}
              material={materials['Neon bleu1']}
              position={[32.774, -337.029, 402.175]}
              rotation={[0.885, -0.946, -2.956]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_3.geometry}
              material={materials['Neon bleu1']}
              position={[30.605, -385.149, 338.623]}
              rotation={[0.885, -0.946, 2.732]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_5.geometry}
              material={materials['Neon bleu1']}
              position={[21.794, -367.935, 340.367]}
              rotation={[0.885, -0.946, 2.282]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_7.geometry}
              material={materials['Neon bleu1']}
              position={[16.359, -352.702, 347.082]}
              rotation={[0.885, -0.946, 2.024]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001.geometry}
              material={materials['Neon bleu1']}
              position={[13.752, -336.014, 361.768]}
              rotation={[0.885, -0.946, -1.744]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials['Neon bleu1']}
              position={[17.218, -330.995, 375.489]}
              rotation={[0.885, -0.946, -2.161]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003.geometry}
              material={materials['Neon bleu1']}
              position={[23.686, -331.119, 389.498]}
              rotation={[0.885, -0.946, -2.575]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials['Neon bleu1']}
              position={[61.614, -400.74, 387.462]}
              rotation={[0.885, -0.946, -1.771]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials['Neon bleu1']}
              position={[57.689, -406.595, 371.713]}
              rotation={[0.885, -0.946, -2.257]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006.geometry}
              material={materials['Neon bleu1']}
              position={[50.194, -405.437, 356.718]}
              rotation={[0.885, -0.946, -2.671]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007.geometry}
              material={materials['Neon bleu1']}
              position={[40.643, -397.966, 344.938]}
              rotation={[0.885, -0.946, 3.139]}
              scale={0.74}
            />
            <group
              position={[-0.252, 18.579, -66.212]}
              rotation={[-1.225, -Math.PI / 2, 0]}
              scale={0.74}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4001.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4002.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4003.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4004.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4005.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4006.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4007.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4008.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4009.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4010.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4011.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4012.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4013.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4014.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4015.geometry}
                material={materials['Neon bleu1']}
                position={[-282.892, -695.438, -22.448]}
                rotation={[0.554, -0.305, 0.001]}
              />
            </group>
            <group position={[7.02, 0, -51.905]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.back_part.geometry}
                material={materials['Material.003']}
                position={[23.132, -378.853, 459.901]}
                rotation={[0.885, -0.946, 0.799]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.back.geometry}
                  material={materials['Material.004']}
                  position={[-2.22, -0.642, -21.529]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                />
              </mesh>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.main_part.geometry}
                material={materials['Material.003']}
                position={[58.413, -347.979, 449.373]}
                rotation={[-0.017, 0.42, 0.477]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.strap.geometry}
              material={materials.Material}
              position={[40.864, -399.324, 346.579]}
              rotation={[-0.017, 0.42, 0.477]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.strap001.geometry}
              material={materials.Material}
              position={[33.112, -358.813, 376.705]}
              rotation={[-0.017, 0.42, 0.477]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/braceletOSKI.glb')
