/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Brecelet(props) {
  const { nodes, materials } = useGLTF('/bracelet.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.455, -0.076, -0.539]} scale={0.002}>
        <group position={[119.197, 0, 0]}>
          <group
            position={[-37.421, 179.812, 474.859]}
            rotation={[1.168, 1.207, -0.053]}
            scale={0.531}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -336.243, 323.887]}
              rotation={[-2.529, -1.571, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_3.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -389.15, 264.221]}
              rotation={[-1.934, -1.571, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_5.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -369.81, 262.492]}
              rotation={[-1.483, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_7.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -352.797, 266.648]}
              rotation={[-1.225, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -334.305, 279.257]}
              rotation={[2.543, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -328.926, 293.276]}
              rotation={[2.96, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -329.342, 308.701]}
              rotation={[-2.909, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder004.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -407.658, 321.206]}
              rotation={[2.57, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder005.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -413.937, 305.135]}
              rotation={[3.056, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder006.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -412.339, 288.408]}
              rotation={[-2.814, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder007.geometry}
              material={materials['Neon bleu1']}
              position={[44.845, -403.698, 273.876]}
              rotation={[-2.34, -Math.PI / 2, 0]}
              scale={0.74}
            />
            <group
              position={[-0.252, 18.579, -66.212]}
              rotation={[-1.225, -Math.PI / 2, 0]}
              scale={0.74}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4001.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4002.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4003.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4004.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4005.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4006.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4007.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4008.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4009.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4010.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4011.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4012.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4013.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4014.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh_4015.geometry}
                material={materials['Neon bleu1']}
                position={[-319.831, -593.213, -60.943]}
              />
            </group>
            <group position={[7.02, 0, -51.905]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.back_part.geometry}
                material={materials['Material.003']}
                position={[14.608, -371.431, 379.367]}
                rotation={[0, -1.571, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.back.geometry}
                  material={materials['Material.004']}
                  position={[-2.22, -0.642, -21.529]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                />
              </mesh>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.main_part.geometry}
                material={materials['Material.003']}
                position={[61.101, -360.502, 384.646]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.strap.geometry}
              material={materials.Material}
              position={[43.801, -404.72, 275.443]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.strap001.geometry}
              material={materials.Material}
              position={[44.693, -360.18, 300.426]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bracelet.glb')
